theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
cursorcolumn = true


[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true


